import 'dart:math';

class MotivationalService {
  static const List<String> phrases = [
    'Tu esfuerzo de hoy será tu logro de mañana.',
    'Cree en tu proceso, incluso cuando sea difícil.',
    'Paso a paso también se llega lejos.',
    'No te rindas, estás más cerca de lo que crees.',
    'El éxito comienza con la decisión de intentarlo.',
    'Aprende, equivócate y vuelve a intentar.',
    'Tu futuro se construye con lo que haces hoy.',
    'Respira, que no todo tiene que resolverse hoy.',
    'Tu estrés no paga renta, libéralo de tu mente.',
    'Un mal día no significa una mala vida.',
    'Paso a paso también se llega.',
    'Encuentra calma en el momento presente.',
    'Tu paz mental es tu mayor tesoro.',
    'Cada día es una nueva oportunidad para empezar.',
    'Confía en lo que viene, tu fuerza es real.',
    'Respira hondo, todo pasa.',
    'Crea espacio para tu bienestar.',
    'Date crédito por lo lejos que has llegado.',
    'Hoy sobrevivir ya cuenta como productividad.',
    'Descansa sin sentir culpa.',
    'Tu mente merece vacaciones de cinco minutos.',
    'No te presiones tanto, eres humano.',
    'El estrés grita, pero tu paz habla más fuerte.',
    'Tú puedes con esto y con más.',
    'Dormir es un acto de amor propio.',
    'La paciencia contigo mismo es clave.',
    'Lo estás haciendo mejor de lo que crees.',
    'Tu valor no depende de tus tareas.',
    'Si llegaste hasta aquí, puedes seguir adelante.',
    'Tu mente también necesita desconectarse.',
    'Está bien parar un rato, no eres una máquina.',
    'Un día pesado no define quién eres.',
    'No te compares, camina a tu propio ritmo.',
    'El estrés no merece protagonismo hoy.',
    'Mantén la calma y continúa.',
    'Respira antes de sobrepensar.',
    'Un paso pequeño sigue siendo un paso.',
    'Tu paz mental vale más que todo.',
    'El mundo puede esperar mientras respiras.',
    'Tu bienestar importa siempre.',
    'No cargues con todo tú solo.',
    'Cada pequeño avance te acerca a tu meta.',
    'Hoy no necesitas perfección, solo seguir.',
    'Respira, sonríe un poquito y continúa.',
    'La calma comienza con una respiración.',
    'Tu bienestar es tu prioridad.',
    'Confía en ti, tienes las respuestas.',
    'Sigue brillando a tu manera.',
    'El estrés llega, pero también se va.',
    'Todo mejora después de un buen descanso.',
    'Puedes reiniciar las veces que necesites.',
    'El estrés no define tu capacidad.',
    'Tu proceso merece paciencia y amor.',
    'Incluso yendo lento estás avanzando.',
    'No te dejes llevar por pensamientos negativos.',
    'Hoy puede ser difícil, pero tú eres fuerte.',
    'Está permitido no poder con todo.',
    'La vida se trata de vivir en armonía.',
    'Un resultado no define todo tu futuro.',
    'Tu mente cansada necesita descanso.',
    'No todo tiene que salir perfecto.',
    'Haz las paces con avanzar poco a poco.',
    'Tu paz mental va primero, siempre.',
    'Si te caes, descansa y vuelve a levantarte.',
    'Cuida tu cuerpo y tu mente por igual.',
    'Eres más fuerte que este momento.',
    'Disfruta del camino hacia tus metas.',
    'La calma también se entrena diariamente.',
    'Todo gran logro empezó con constancia.',
    'Respira, ya has superado retos peores.',
    'Está bien pedir ayuda cuando la necesitas.',
    'Tu mente merece tranquilidad hoy.',
    'Cuidar de ti no es egoísmo, es necesario.',
    'Mantén el enfoque en tu bienestar.',
    'Si pudiste levantarte hoy, ya vas ganando.',
    'El mañana será un día más luminoso.',
    'Abraza tu presente con paciencia.',
    'El cambio comienza en tu interior.',
    'Confía en tus capacidades.',
    'Sigue adelante con paso firme.',
    'Nunca subestimes tu propio potencial.',
    'Tú también mereces sentir orgullo de ti.'
  ];

  static String getRandomPhrase() {
    final random = Random();
    return phrases[random.nextInt(phrases.length)];
  }
}
